name: Ruby

on: [push,pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-x64
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false
    - name: Set up Ruby
      uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
      with:
        ruby-version: 3.0.0
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.3
        bundle install
        bundle exec rake
