name: Ruby

on: [push,pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-x64
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false
    - name: Set up Ruby
      uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
      with:
        ruby-version: 3.0.0
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.3
        bundle install
        bundle exec rake
